version : 2

sources:
  - name: airbnb
    description: raw airbnb data
    tables:
      - name: calendar
      - name: listing

models:
  - name: stg_airbnb
    description: join 2 raw datasets calendar and lisitng
    columns:
      - name: "(listing_id || '_' || date)"
        tests:
          - unique
          - not_null